### PR TITLE
#39/ Put a page to select the property TYPE

### PR DESCRIPTION
**Pull request by Tech-Dex**

### CODE REVIEW

**Comment by Tech-Dex** [comment]
image
image

**Comment by ezl** [comment]
@Tech-Dex is this a screenshot? Does this mean that on a mobile screen, each button is on it's own row?

I think these should be at most 1/2 width even on the smallest screen.

**Comment by Tech-Dex** [comment]
Ok, so you want one alongside another

**Comment by ezl** [comment]
yes. Sorry, my fault, I wasn't very clear. The screen that I linked to in the ticket was intended to be the mobile view.

So maybe do cols=6, md=3

**Pull request merged**
